// app/vibeComponents.ts

export type VibeComponentKind =
  | "app-card"
  | "pricing"
  | "hero"
  | "dashboard"
  | "cta"
  | "testimonial"
  | "linkedin-post";

export type VibeComponentConfig = {
  id: string;
  kind: VibeComponentKind;
  title: string;
  subtitle?: string;
  description?: string;
  tone: "light" | "dark";
  // Tailwind classes – explicit strings (no string interpolation in GameClient)
  bgClass: string;
  textClass: string;
  borderClass: string;
  accentClass: string;
  size: "sm" | "md" | "lg";
  imageSrc?: string; // optional: LinkedIn screenshots etc.
};

export const VIBE_COMPONENTS: VibeComponentConfig[] = [
  {
    id: "hero-gradient-collab",
    kind: "hero",
    title: "Async Collaboration Hub",
    subtitle: "Where teams align in real-time, asynchronously.",
    description: "A hero panel with soft gradients and floating pills.",
    tone: "light",
    bgClass:
      "bg-gradient-to-r from-sky-100 via-indigo-100 to-violet-100 backdrop-blur-sm",
    textClass: "text-slate-800",
    borderClass: "border-sky-200",
    accentClass: "bg-sky-400",
    size: "lg",
  },
  {
    id: "pricing-modern",
    kind: "pricing",
    title: "Growth Plan",
    subtitle: "$49 / seat / month",
    description: "Perfect for scaling teams that love alignment.",
    tone: "light",
    bgClass: "bg-white",
    textClass: "text-slate-800",
    borderClass: "border-emerald-200",
    accentClass: "bg-emerald-400",
    size: "md",
  },
  {
    id: "dashboard-dark",
    kind: "dashboard",
    title: "Engagement Metrics",
    subtitle: "Week-over-week delta",
    description: "A faux dashboard tile with tiny charts.",
    tone: "dark",
    bgClass: "bg-slate-900",
    textClass: "text-slate-50",
    borderClass: "border-slate-700",
    accentClass: "bg-cyan-400",
    size: "md",
  },
  {
    id: "cta-pill",
    kind: "cta",
    title: "Book a Demo",
    subtitle: "See how leading teams align in days.",
    tone: "light",
    bgClass: "bg-gradient-to-r from-violet-500 to-fuchsia-500",
    textClass: "text-white",
    borderClass: "border-violet-400",
    accentClass: "bg-white/80",
    size: "sm",
  },
  {
    id: "testimonial-card",
    kind: "testimonial",
    title: "“This transformed our workflows.”",
    subtitle: "VP Product, Global SaaS Co.",
    tone: "light",
    bgClass: "bg-white",
    textClass: "text-slate-800",
    borderClass: "border-amber-200",
    accentClass: "bg-amber-400",
    size: "sm",
  },
  {
    id: "app-card-glass",
    kind: "app-card",
    title: "Alignment Canvas",
    subtitle: "Map initiatives, owners, and outcomes.",
    description: "Glassmorphism-style app card.",
    tone: "light",
    bgClass: "bg-white/70 backdrop-blur-md",
    textClass: "text-slate-900",
    borderClass: "border-indigo-100",
    accentClass: "bg-indigo-400",
    size: "md",
  },
  {
    id: "hero-dark-neon",
    kind: "hero",
    title: "Future-Proof Stack",
    subtitle: "Operationalize AI-first rituals.",
    tone: "dark",
    bgClass: "bg-gradient-to-br from-slate-900 via-slate-950 to-zinc-900",
    textClass: "text-slate-50",
    borderClass: "border-lime-400/40",
    accentClass: "bg-lime-400",
    size: "lg",
  },
  {
    id: "pricing-brutalist",
    kind: "pricing",
    title: "Enterprise Alignment",
    subtitle: "Talk to sales",
    tone: "light",
    bgClass: "bg-yellow-100",
    textClass: "text-slate-900",
    borderClass: "border-slate-900",
    accentClass: "bg-slate-900",
    size: "md",
  },
  {
    id: "dashboard-kpi",
    kind: "dashboard",
    title: "NPS • 72",
    subtitle: "Stakeholder sentiment this quarter",
    tone: "light",
    bgClass: "bg-emerald-50",
    textClass: "text-slate-900",
    borderClass: "border-emerald-200",
    accentClass: "bg-emerald-400",
    size: "sm",
  },
  {
    id: "linkedin-generic",
    kind: "linkedin-post",
    title: "Feeling grateful to share…",
    subtitle: "Reflections on an incredible journey.",
    description: "Generic LinkedIn block with avatar and image slot.",
    tone: "light",
    bgClass: "bg-white",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-sky-400",
    size: "lg",
    // imageSrc: "/assets/linkedin/linkedin1.jpg",
  },
  {
    id: "linkedin-dark",
    kind: "linkedin-post",
    title: "Honoured to finally announce…",
    subtitle: "Joining an incredible team building the future.",
    description: "Dark LinkedIn variant.",
    tone: "dark",
    bgClass: "bg-slate-900",
    textClass: "text-slate-50",
    borderClass: "border-slate-700",
    accentClass: "bg-sky-400",
    size: "lg",
    // imageSrc: "/assets/linkedin/linkedin2.jpg",
  },
  {
    id: "cta-outline",
    kind: "cta",
    title: "Start your alignment journey",
    subtitle: "Onboard your first team in under a week.",
    tone: "light",
    bgClass: "bg-white",
    textClass: "text-slate-900",
    borderClass: "border-sky-300",
    accentClass: "bg-sky-400",
    size: "sm",
  },
    {
    id: "hero-alignment-os-1",
    kind: "hero",
    title: "Aligned Impact OS",
    subtitle: "Turn messy signals into a shared narrative.",
    description: "A full-bleed hero with layered gradients, overlaid faux metrics, and a primary CTA button.",
    tone: "light",
    bgClass: "bg-gradient-to-r from-sky-100 via-indigo-100 to-violet-100",
    textClass: "text-slate-800",
    borderClass: "border-sky-200",
    accentClass: "bg-sky-400",
    size: "lg"
    },
    {
    id: "hero-future-proof-stack-2",
    kind: "hero",
    title: "Future-Proof Stack for Operators",
    subtitle: "Operationalize async rituals for high-velocity teams.",
    description: "Hero banner with oversized typography, floating pills, and ghosted screenshots.",
    tone: "dark",
    bgClass: "bg-gradient-to-br from-slate-900 via-slate-950 to-black",
    textClass: "text-slate-50",
    borderClass: "border-slate-700",
    accentClass: "bg-emerald-400",
    size: "lg"
    },
    {
    id: "hero-ecosystem-rituals-3",
    kind: "hero",
    title: "Ecosystem Rituals Hub",
    subtitle: "Where stakeholders align without another meeting.",
    description: "Glassmorphism hero with blurred cards and subtle depth shadows.",
    tone: "light",
    bgClass: "bg-white/70 backdrop-blur-md",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-amber-400",
    size: "lg"
    },
    {
    id: "hero-signal-over-noise-4",
    kind: "hero",
    title: "Signal Over Noise Control Center",
    subtitle: "See the narrative behind every metric.",
    description: "Dark hero with neon edges, tiny graphs, and fake toggles for journeys and cohorts.",
    tone: "dark",
    bgClass: "bg-gradient-to-br from-slate-900 via-slate-950 to-zinc-900",
    textClass: "text-slate-50",
    borderClass: "border-zinc-800",
    accentClass: "bg-cyan-400",
    size: "lg"
    },
    {
    id: "hero-stakeholder-journey-5",
    kind: "hero",
    title: "Stakeholder Journey Canvas",
    subtitle: "Map owners, outcomes, and decision rights in one place.",
    description: "Soft 3D blobs in the background with a centered CTA and stacked avatars.",
    tone: "light",
    bgClass: "bg-emerald-50",
    textClass: "text-slate-900",
    borderClass: "border-emerald-200",
    accentClass: "bg-emerald-400",
    size: "lg"
    },
    {
    id: "hero-north-star-metrics-6",
    kind: "hero",
    title: "North Star Metrics, Explained",
    subtitle: "From vanity dashboards to narrative clarity.",
    description: "Oversized headline with dual CTAs and fake KPI chips.",
    tone: "dark",
    bgClass: "bg-slate-900",
    textClass: "text-slate-50",
    borderClass: "border-slate-700",
    accentClass: "bg-amber-400",
    size: "lg"
    },
    {
    id: "hero-operator-os-7",
    kind: "hero",
    title: "Operator OS for Outcome-Driven Squads",
    subtitle: "Align roadmaps, rituals, and resources in days.",
    description: "Two-column hero with card stack illustration and checklist bullets.",
    tone: "light",
    bgClass: "bg-slate-50",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-fuchsia-400",
    size: "lg"
    },
    {
    id: "hero-async-offsite-8",
    kind: "hero",
    title: "The Async Offsite, Every Week",
    subtitle: "Replace the yearly slide deck with living rituals.",
    description: "Gradient background, timeline pills, and a faux calendar layout.",
    tone: "dark",
    bgClass: "bg-gradient-to-r from-fuchsia-500 to-violet-500",
    textClass: "text-slate-50",
    borderClass: "border-emerald-500/40",
    accentClass: "bg-lime-400",
    size: "lg"
    },
    
    {
    id: "pricing-starter-alignment-9",
    kind: "pricing",
    title: "Starter Alignment",
    subtitle: "$19 / seat / month",
    description: "Lightweight plan tile with one highlighted bullet and fake toggle for yearly billing.",
    tone: "light",
    bgClass: "bg-white",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-sky-400",
    size: "md"
    },
    {
    id: "pricing-growth-rituals-10",
    kind: "pricing",
    title: "Growth Rituals",
    subtitle: "$49 / seat / month",
    description: "Middle pricing card with a glowing border and ‘Most aligned’ badge.",
    tone: "light",
    bgClass: "bg-emerald-50",
    textClass: "text-slate-900",
    borderClass: "border-emerald-200",
    accentClass: "bg-emerald-400",
    size: "md"
    },
    {
    id: "pricing-scale-ecosystem-11",
    kind: "pricing",
    title: "Scale Ecosystem",
    subtitle: "Usage-based, talk to sales",
    description: "Enterprise tile with logos strip and bullet list of governance controls.",
    tone: "dark",
    bgClass: "bg-slate-900",
    textClass: "text-slate-50",
    borderClass: "border-slate-700",
    accentClass: "bg-cyan-400",
    size: "md"
    },
    {
    id: "pricing-founder-rituals-12",
    kind: "pricing",
    title: "Founder Rituals",
    subtitle: "$29 / seat / month",
    description: "Brutalist block with strong borders, big numbers, and minimal copy.",
    tone: "light",
    bgClass: "bg-yellow-100",
    textClass: "text-slate-900",
    borderClass: "border-yellow-500",
    accentClass: "bg-rose-500",
    size: "md"
    },
    {
    id: "pricing-retro-lite-13",
    kind: "pricing",
    title: "Retro Lite",
    subtitle: "$9 / seat / month",
    description: "Small plan tile with fake checkmarks and ‘async retros only’ tag.",
    tone: "light",
    bgClass: "bg-slate-50",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-amber-400",
    size: "sm"
    },
    {
    id: "pricing-metrics-plus-14",
    kind: "pricing",
    title: "Metrics Plus",
    subtitle: "Custom pricing for global teams",
    description: "Pricing card with stacked badges for SSO, SLA, and ‘Executive dashboards’.",
    tone: "dark",
    bgClass: "bg-zinc-900",
    textClass: "text-slate-50",
    borderClass: "border-zinc-800",
    accentClass: "bg-indigo-400",
    size: "md"
    },
    {
    id: "pricing-async-everywhere-15",
    kind: "pricing",
    title: "Async Everywhere",
    subtitle: "$39 / seat / month",
    description: "Soft card with toggles for regions, workspaces, and ‘OKR rituals’.",
    tone: "light",
    bgClass: "bg-sky-50",
    textClass: "text-slate-900",
    borderClass: "border-sky-200",
    accentClass: "bg-cyan-400",
    size: "md"
    },
    {
    id: "pricing-enterprise-governance-16",
    kind: "pricing",
    title: "Enterprise Governance",
    subtitle: "Talk to sales",
    description: "Dark plan tile with lock icons, compliance badges, and a highlighted ‘Request deck’ CTA.",
    tone: "dark",
    bgClass: "bg-gradient-to-br from-slate-900 via-slate-950 to-black",
    textClass: "text-slate-50",
    borderClass: "border-neutral-800",
    accentClass: "bg-emerald-400",
    size: "lg"
    },
    
    {
    id: "dashboard-alignment-kpi-17",
    kind: "dashboard",
    title: "Alignment KPI",
    subtitle: "+37% engagement delta this quarter",
    description: "Tiny donut chart, sparkline, and pill showing ‘green’ trend.",
    tone: "light",
    bgClass: "bg-emerald-50",
    textClass: "text-slate-900",
    borderClass: "border-emerald-200",
    accentClass: "bg-emerald-400",
    size: "sm"
    },
    {
    id: "dashboard-stakeholder-sentiment-18",
    kind: "dashboard",
    title: "Stakeholder Sentiment",
    subtitle: "NPS • 72",
    description: "Faux sentiment graph with smiling avatars and optimistic labels.",
    tone: "light",
    bgClass: "bg-white",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-amber-400",
    size: "md"
    },
    {
    id: "dashboard-velocity-rituals-19",
    kind: "dashboard",
    title: "Velocity Rituals",
    subtitle: "Cadence health across squads",
    description: "Heatmap-style tile with columns for standups, retros, and reviews.",
    tone: "dark",
    bgClass: "bg-slate-900",
    textClass: "text-slate-50",
    borderClass: "border-slate-700",
    accentClass: "bg-cyan-400",
    size: "md"
    },
    {
    id: "dashboard-north-star-20",
    kind: "dashboard",
    title: "North Star Progress",
    subtitle: "Week-over-week story of impact",
    description: "Line chart with playful dots and a big percentage at the top-right.",
    tone: "light",
    bgClass: "bg-slate-50",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-sky-400",
    size: "md"
    },
    {
    id: "dashboard-experiment-stream-21",
    kind: "dashboard",
    title: "Experiment Stream",
    subtitle: "9 live bets across the funnel",
    description: "Multi-column tile with chips for ‘Runway’, ‘Owner’, and ‘Impact’.",
    tone: "dark",
    bgClass: "bg-zinc-900",
    textClass: "text-slate-50",
    borderClass: "border-zinc-800",
    accentClass: "bg-fuchsia-400",
    size: "md"
    },
    {
    id: "dashboard-ops-health-22",
    kind: "dashboard",
    title: "Ops Health Index",
    subtitle: "From reactive to proactive",
    description: "Gauge widget with three zones and faux annotation text.",
    tone: "light",
    bgClass: "bg-amber-50",
    textClass: "text-slate-900",
    borderClass: "border-amber-200",
    accentClass: "bg-amber-400",
    size: "sm"
    },
    {
    id: "dashboard-ecosystem-map-23",
    kind: "dashboard",
    title: "Ecosystem Map",
    subtitle: "Teams, tools, and touchpoints",
    description: "Node-link visualization implied with dots, lines, and gradient chips.",
    tone: "dark",
    bgClass: "bg-slate-950",
    textClass: "text-slate-50",
    borderClass: "border-neutral-800",
    accentClass: "bg-lime-400",
    size: "md"
    },
    {
    id: "dashboard-retention-story-24",
    kind: "dashboard",
    title: "Retention Story",
    subtitle: "Why customers actually stay",
    description: "Stacked area chart with cohort labels and little emoji markers.",
    tone: "light",
    bgClass: "bg-sky-50",
    textClass: "text-slate-900",
    borderClass: "border-sky-200",
    accentClass: "bg-cyan-400",
    size: "md"
    },
    {
    id: "dashboard-ops-pager-25",
    kind: "dashboard",
    title: "Ops Pager",
    subtitle: "Risks, blockers, and nudges",
    description: "List layout with severity pills and ‘Assign owner’ buttons.",
    tone: "dark",
    bgClass: "bg-neutral-900",
    textClass: "text-slate-50",
    borderClass: "border-neutral-800",
    accentClass: "bg-rose-500",
    size: "sm"
    },
    {
    id: "dashboard-people-insights-26",
    kind: "dashboard",
    title: "People Insights",
    subtitle: "Who is carrying the narrative",
    description: "Avatar grid with contribution meters and faux tooltips.",
    tone: "light",
    bgClass: "bg-white",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-emerald-400",
    size: "md"
    },
    
    {
    id: "app-card-alignment-canvas-27",
    kind: "app-card",
    title: "Alignment Canvas",
    subtitle: "Map initiatives, owners, and outcomes.",
    description: "Glassmorphism app card with layered panels and tags.",
    tone: "light",
    bgClass: "bg-white/70 backdrop-blur-md",
    textClass: "text-slate-900",
    borderClass: "border-indigo-100",
    accentClass: "bg-indigo-400",
    size: "md"
    },
    {
    id: "app-card-ops-inbox-28",
    kind: "app-card",
    title: "Ops Inbox",
    subtitle: "One place for all escalations.",
    description: "Card with list items, status pills, and fake search bar.",
    tone: "dark",
    bgClass: "bg-slate-900/70 backdrop-blur-lg",
    textClass: "text-slate-50",
    borderClass: "border-slate-700",
    accentClass: "bg-amber-400",
    size: "md"
    },
    {
    id: "app-card-ritual-scheduler-29",
    kind: "app-card",
    title: "Ritual Scheduler",
    subtitle: "Codify your weekly cadences.",
    description: "Compact card with calendar chips and toggle switches.",
    tone: "light",
    bgClass: "bg-slate-50",
    textClass: "text-slate-900",
    borderClass: "border-slate-200",
    accentClass: "bg-emerald-400",
    size: "sm"
    },
    {
    id: "app-card-decision-log-30",
    kind: "app-card",
    title: "Decision Log",
    subtitle: "Never lose context again.",
    description: "Two-column layout with timeline, owners, and impact tags.",
    tone: "dark",
    bgClass: "bg-zinc-900",
    textClass: "text-slate-50",
    borderClass: "border-zinc-800",
    accentClass: "bg-sky-400",
    size: "md"
    },
    {
        id: "app-card-exec-brief-31",
        kind: "app-card",
        title: "Exec Brief",
        subtitle: "Three slides instead of thirty.",
        description: "Minimal card with faux slide thumbnails and CTA.",
        tone: "light",
        bgClass: "bg-white",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-fuchsia-400",
        size: "md"
        },
        {
        id: "app-card-portfolio-view-32",
        kind: "app-card",
        title: "Portfolio View",
        subtitle: "Zoom out on the entire bet stack.",
        description: "Multi-tile grid with hover states implied by shadows.",
        tone: "dark",
        bgClass: "bg-slate-950",
        textClass: "text-slate-50",
        borderClass: "border-neutral-800",
        accentClass: "bg-lime-400",
        size: "lg"
        },
        {
        id: "app-card-feedback-stream-33",
        kind: "app-card",
        title: "Feedback Stream",
        subtitle: "Turn opinions into operating leverage.",
        description: "Card with speech bubbles, emoji reactions, and sentiment bars.",
        tone: "light",
        bgClass: "bg-emerald-50",
        textClass: "text-slate-900",
        borderClass: "border-emerald-200",
        accentClass: "bg-emerald-400",
        size: "md"
        },
        {
        id: "app-card-risk-register-34",
        kind: "app-card",
        title: "Risk Register",
        subtitle: "Name the dragons before they grow.",
        description: "Table-like layout with severity chips and owners.",
        tone: "dark",
        bgClass: "bg-neutral-900",
        textClass: "text-slate-50",
        borderClass: "border-neutral-800",
        accentClass: "bg-rose-500",
        size: "md"
        },
        {
        id: "app-card-learning-loop-35",
        kind: "app-card",
        title: "Learning Loop Tracker",
        subtitle: "From experiments to playbooks.",
        description: "Card with loop diagram and progress steps.",
        tone: "light",
        bgClass: "bg-sky-50",
        textClass: "text-slate-900",
        borderClass: "border-sky-200",
        accentClass: "bg-cyan-400",
        size: "sm"
        },
        {
        id: "app-card-ai-copilot-36",
        kind: "app-card",
        title: "AI Copilot for Ops",
        subtitle: "Ask one question, get the narrative.",
        description: "Dark glass card with chat bubbles and glowing cursor.",
        tone: "dark",
        bgClass: "bg-slate-900/70 backdrop-blur-md",
        textClass: "text-slate-50",
        borderClass: "border-slate-700",
        accentClass: "bg-indigo-400",
        size: "md"
        },
        
        {
        id: "cta-start-alignment-37",
        kind: "cta",
        title: "Start your alignment journey",
        subtitle: "Onboard your first team in under a week.",
        tone: "light",
        bgClass: "bg-gradient-to-r from-violet-500 to-fuchsia-500",
        textClass: "text-white",
        borderClass: "border-violet-400",
        accentClass: "bg-white/80",
        size: "sm"
        },
        {
        id: "cta-book-demo-38",
        kind: "cta",
        title: "Book a narrative demo",
        subtitle: "See your own metrics turned into a story.",
        tone: "dark",
        bgClass: "bg-slate-900",
        textClass: "text-slate-50",
        borderClass: "border-slate-700",
        accentClass: "bg-emerald-400",
        size: "sm"
        },
        {
        id: "cta-join-beta-39",
        kind: "cta",
        title: "Join the operator beta",
        subtitle: "Limited seats for teams who ship weekly.",
        tone: "light",
        bgClass: "bg-white",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-sky-400",
        size: "sm"
        },
        {
        id: "cta-download-playbook-40",
        kind: "cta",
        title: "Download the rituals playbook",
        subtitle: "Five templates to reset your cadence.",
        tone: "light",
        bgClass: "bg-amber-50",
        textClass: "text-slate-900",
        borderClass: "border-amber-200",
        accentClass: "bg-amber-400",
        size: "md"
        },
        {
        id: "cta-async-offsite-41",
        kind: "cta",
        title: "Run your first async offsite",
        subtitle: "No flights, just alignment.",
        tone: "dark",
        bgClass: "bg-gradient-to-br from-slate-900 via-slate-950 to-black",
        textClass: "text-slate-50",
        borderClass: "border-neutral-800",
        accentClass: "bg-cyan-400",
        size: "md"
        },
        {
        id: "cta-invite-stakeholders-42",
        kind: "cta",
        title: "Invite your stakeholders",
        subtitle: "Turn them into co-authors of the journey.",
        tone: "light",
        bgClass: "bg-slate-50",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-emerald-400",
        size: "sm"
        },
        {
        id: "cta-launch-ops-os-43",
        kind: "cta",
        title: "Launch your Ops OS",
        subtitle: "Make every project legible overnight.",
        tone: "dark",
        bgClass: "bg-zinc-900",
        textClass: "text-slate-50",
        borderClass: "border-zinc-800",
        accentClass: "bg-fuchsia-400",
        size: "md"
        },
        {
        id: "cta-upgrade-now-44",
        kind: "cta",
        title: "Upgrade to aligned impact",
        subtitle: "Unlock advanced dashboards and governance.",
        tone: "light",
        bgClass: "bg-emerald-50",
        textClass: "text-slate-900",
        borderClass: "border-emerald-200",
        accentClass: "bg-emerald-400",
        size: "sm"
        },
        
        {
        id: "testimonial-vp-product-45",
        kind: "testimonial",
        title: "“We finally have one narrative for the whole org.”",
        subtitle: "VP Product, Global SaaS Co.",
        description: "Compact praise tile with avatar, name, and faux logo.",
        tone: "light",
        bgClass: "bg-white",
        textClass: "text-slate-900",
        borderClass: "border-amber-200",
        accentClass: "bg-amber-400",
        size: "sm"
        },
        {
        id: "testimonial-head-strategy-46",
        kind: "testimonial",
        title: "“Our exec meetings went from chaos to clarity.”",
        subtitle: "Head of Strategy, Fintech",
        description: "Card with quote, role label, and star rating row.",
        tone: "dark",
        bgClass: "bg-slate-900",
        textClass: "text-slate-50",
        borderClass: "border-slate-700",
        accentClass: "bg-emerald-400",
        size: "sm"
        },
        {
        id: "testimonial-director-ops-47",
        kind: "testimonial",
        title: "“The rituals actually stuck this time.”",
        subtitle: "Director of Ops, Marketplace",
        description: "Horizontal layout with quotation marks and tiny KPI tags.",
        tone: "light",
        bgClass: "bg-slate-50",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-sky-400",
        size: "md"
        },
        {
        id: "testimonial-cpo-seriesb-48",
        kind: "testimonial",
        title: "“It gave us a common language for impact.”",
        subtitle: "CPO, Series B Startup",
        description: "Glass card with gradient accent bar and logo cloud.",
        tone: "dark",
        bgClass: "bg-slate-900/70 backdrop-blur-md",
        textClass: "text-slate-50",
        borderClass: "border-zinc-800",
        accentClass: "bg-fuchsia-400",
        size: "md"
        },
        {
        id: "testimonial-head-people-49",
        kind: "testimonial",
        title: "“Our people feel part of the story now.”",
        subtitle: "Head of People, Remote-first",
        description: "Card with overlapping avatars and ‘Engagement up’ chip.",
        tone: "light",
        bgClass: "bg-emerald-50",
        textClass: "text-slate-900",
        borderClass: "border-emerald-200",
        accentClass: "bg-emerald-400",
        size: "sm"
        },
        {
        id: "testimonial-ceo-portfolio-50",
        kind: "testimonial",
        title: "“Best slide we’ve shown to the board all year.”",
        subtitle: "CEO, Portfolio Company",
        description: "Wide testimonial with signature line and faux board logos.",
        tone: "dark",
        bgClass: "bg-neutral-900",
        textClass: "text-slate-50",
        borderClass: "border-neutral-800",
        accentClass: "bg-amber-400",
        size: "md"
        },
        {
        id: "testimonial-vp-engineering-51",
        kind: "testimonial",
        title: "“Finally a tool that speaks both code and strategy.”",
        subtitle: "VP Engineering, Platform",
        description: "Block with code-style accent and metric chips.",
        tone: "light",
        bgClass: "bg-white",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-indigo-400",
        size: "md"
        },
        {
        id: "testimonial-head-revenue-52",
        kind: "testimonial",
        title: "“We stopped arguing about dashboards and started fixing them.”",
        subtitle: "Head of Revenue, B2B SaaS",
        description: "Quote card with revenue icon and ‘Revenue ops approved’ tag.",
        tone: "dark",
        bgClass: "bg-slate-950",
        textClass: "text-slate-50",
        borderClass: "border-zinc-800",
        accentClass: "bg-rose-500",
        size: "sm"
        },
        
        {
        id: "linkedin-post-grateful-chapter-53",
        kind: "linkedin-post",
        title: "Grateful to announce a new chapter",
        subtitle: "From firefighting to future-proofing our operating system.",
        description: "LinkedIn post layout with avatar, name, and multi-line text preview.",
        tone: "light",
        bgClass: "bg-white",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-sky-400",
        size: "lg",
        imageSrc: "/assets/linkedin/linkedin1.jpg"
        },
        {
        id: "linkedin-post-humbled-journey-54",
        kind: "linkedin-post",
        title: "Humbled by this alignment journey",
        subtitle: "Some messy, honest reflections from the last 12 months.",
        description: "Thought-leadership block with long intro paragraph and fake ‘see more’ truncation.",
        tone: "dark",
        bgClass: "bg-slate-900",
        textClass: "text-slate-50",
        borderClass: "border-slate-700",
        accentClass: "bg-emerald-400",
        size: "lg",
        imageSrc: "/assets/linkedin/linkedin2.jpg"
        },
        {
        id: "linkedin-post-three-lessons-55",
        kind: "linkedin-post",
        title: "3 lessons from scaling stakeholder rituals",
        subtitle: "Thread-style post with emojis and numbered bullets.",
        description: "Post preview with bolded ‘Lesson 1, 2, 3’ structure and engagement row.",
        tone: "light",
        bgClass: "bg-slate-50",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-amber-400",
        size: "lg",
        imageSrc: "/assets/linkedin/linkedin3.jpg"
        },
        {
        id: "linkedin-post-failure-to-clarity-56",
        kind: "linkedin-post",
        title: "From failure metrics to narrative clarity",
        subtitle: "What changing one ritual did to our roadmap debates.",
        description: "LinkedIn block with hero sentence, paragraph text, and fake comment icons.",
        tone: "dark",
        bgClass: "bg-zinc-900",
        textClass: "text-slate-50",
        borderClass: "border-zinc-800",
        accentClass: "bg-fuchsia-400",
        size: "lg",
        imageSrc: "/assets/linkedin/linkedin4.jpg"
        },
        {
        id: "linkedin-post-offsite-reflection-57",
        kind: "linkedin-post",
        title: "Reflections after our first async offsite",
        subtitle: "Spoiler: nobody missed the flights.",
        description: "Post with image slot, quote-style pullout, and tiny reaction avatars.",
        tone: "light",
        bgClass: "bg-white",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-emerald-400",
        size: "lg"
        },
        {
        id: "linkedin-post-ops-thread-58",
        kind: "linkedin-post",
        title: "A small thread on operator mindset",
        subtitle: "Why we over-invested in narrative, not tooling.",
        description: "Thread preview with bullet-style lines and expanded first comment.",
        tone: "dark",
        bgClass: "bg-slate-900",
        textClass: "text-slate-50",
        borderClass: "border-slate-700",
        accentClass: "bg-cyan-400",
        size: "lg"
        },
        {
        id: "linkedin-post-team-wins-59",
        kind: "linkedin-post",
        title: "Celebrating small, compounding team wins",
        subtitle: "Alignment doesn’t happen in one workshop.",
        description: "Post layout with photo strip placeholder and engagement count row.",
        tone: "light",
        bgClass: "bg-slate-50",
        textClass: "text-slate-900",
        borderClass: "border-slate-200",
        accentClass: "bg-sky-400",
        size: "lg"
        },
        {
        id: "linkedin-post-metrics-to-story-60",
        kind: "linkedin-post",
        title: "Turning disconnected metrics into a shared story",
        subtitle: "Some behind-the-scenes of our new operating model.",
        description: "Classic LinkedIn essay card with headline hook, paragraph, and faux ‘Pinned’ badge.",
        tone: "dark",
        bgClass: "bg-slate-900/70 backdrop-blur-md",
        textClass: "text-slate-50",
        borderClass: "border-zinc-800",
        accentClass: "bg-rose-500",
        size: "lg"
        }
];
